<a href="https://colab.research.google.com/github/AbdullahAZaidi/Stereo_Calibration/blob/main/stereo_cal_stereo_alignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
from io import StringIO
from pathlib import Path
import sys
from typing import NamedTuple, Any
import glob
import cv2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import cv2
import h5py
import glob
import numpy as np
import cv2
import os
import time

from google.colab import drive
drive.mount('/content/gdrive')

df = pd.read_excel('/content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Intrinsic_parameters/Intrinsic_parameters.xlsx', dtype={'Unit SN':'string', 'Pair SN':'string'} )
# df_output = pd.DataFrame()

translation_x_min = 390
translation_x_max = 410

translation_y_min = -10
translation_y_max = 10

translation_z_min = -10
translation_z_max = 10

rotation_min = -0.0087
rotation_max = 0.0087

def load_camera_matrix(Camera):
  Fx = df.loc[Camera, ['Fx'][0]]
  Fy = df.loc[Camera, ['Fy'][0]]
  Cx = df.loc[Camera, ['Cx'][0]]
  Cy = df.loc[Camera, ['Cy'][0]]
  
  return np.array([[ Fx,  0.,  Cx ],
                  [ 0.,  Fy,  Cy ],
                  [ 0.,  0.,  1 ]])


def load_dist_coeff(Camera):
  K1 = df.loc[Camera, ['K1'][0]]
  K2 = df.loc[Camera, ['K2'][0]]
  P1 = df.loc[Camera, ['P1'][0]]
  P2 = df.loc[Camera, ['P2'][0]]
  K3 = df.loc[Camera, ['K3'][0]]

  return np.array ([K1, K2, P1, P2, K3])


def translation_x_highlight(val):
    color = 'green' if translation_x_min <val < translation_x_max else 'red'
    return 'color: %s' % color

def translation_y_highlight(val):
    color = 'green' if translation_y_min <val < translation_y_max else 'red'
    return 'color: %s' % color

def translation_z_highlight(val):
    color = 'green' if translation_z_min <val < translation_z_max else 'red'
    return 'color: %s' % color

def rotation_highlight(val):
    color = 'green' if rotation_min <val < rotation_max else 'red'
    return 'color: %s' % color


# df_output = pd.DataFrame()
def write_trans_rot_errors(output, pair):

  vals = {'translation_x': [output[0]],
          'translation_y': [output[1]],
          'translation_z': [output[2]],
          'rotation_x': [output[3]],
          'rotation_y': [output[4]],
          'rotation_z': [output[5]],
          'pair SN': pair
        }

  return vals
  # df_output = pd.DataFrame()
  # df_output_new = df_output.append(pd.DataFrame(vals, columns = ['pair SN','translation_x', 'translation_y', 'translation_z','rotation_x','rotation_y','rotation_z']) )
  # # new_df = pd.concat([df, df], axis=0)
  # return df_output_new


def write_output(sheet, df_output):
  # df.append(df)
  df_output.reset_index(drop=True)
  df_output.style.\
    applymap(translation_x_highlight,subset=['translation_x']).\
    applymap(translation_y_highlight,subset=['translation_y']).\
    applymap(translation_z_highlight,subset=['translation_z']).\
    applymap(rotation_highlight,subset=['rotation_x','rotation_y','rotation_z']).\
    to_excel(sheet, index = True, engine='openpyxl')

def intrinsics_vals(output):

  vals = {'Fx': [output.cam_mat[0,0]],
          'Fy': [output.cam_mat[1,1]],
          'Cx': [output.cam_mat[0,2]],
          'Cy': [output.cam_mat[1,2]],
          'K1': [output.dist_coeffs[0][0]],
          'K2': [output.dist_coeffs[0][1]],
          'K3': [output.dist_coeffs[0][4]],
          'P1': [output.dist_coeffs[0][2]],
          'P2': [output.dist_coeffs[0][3]],
          'K4': 0,
          'K5': 0,
          'K6': 0,
          'Projection Error' : [output.rms_reprojection_err]
        }

  return vals

def write_intrinsics(sheet, left, right):
  df_left = pd.DataFrame(intrinsics_vals(left), columns = ['pairs','Fx', 'Fy', 'Cx','Cy','K1','K2','K3','K4','K5','K6', 'P1','P2', 'Projection Error' ])
  df_right = pd.DataFrame(intrinsics_vals(right),columns = ['pairs','Fx', 'Fy', 'Cx','Cy','K1','K2','K3','K4','K5','K6', 'P1','P2', 'Projection Error' ])

  new_df = pd.concat([df_left, df_right], axis=0)
  # df_left.append(df_right)
  new_df.to_excel(sheet, index = False, engine='openpyxl')
  # df_right.to_excel(sheet, index = False, engine='openpyxl', startrow = 1)
  # df.to_excel(sheet, index = False, header=True)
                  

def _find_checkerboard_corners(tgt_size, imfile_path: Path) -> Any:
    print(f'Loading {imfile_path} ...', file=sys.stderr)
    assert imfile_path.is_file(), f"{imfile_path} is not a valid file"
    im = cv2.imread(str(imfile_path))
    gray_im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
#     plt.imshow(im)

    print('  finding chessboard corners ...', file=sys.stderr)
    pattern_was_found, pixel_corners = cv2.findChessboardCorners(gray_im, tgt_size, flags=cv2.CALIB_CB_FAST_CHECK)
    assert pattern_was_found, f"No corners detected!"
    cv2.cornerSubPix(gray_im, pixel_corners, (11, 11), (-1, 1), (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001))

    if (pixel_corners[0] > pixel_corners[-1]).all():
        print(f'Flipping reversed checkboard detections for {imfile_path}', file=sys.stderr)
        pixel_corners = pixel_corners[::-1]  # Corners must be top-bottom

    print('  writing corner detection visualization ...', file=sys.stderr)
    cv2.drawChessboardCorners(im, tgt_size, pixel_corners, pattern_was_found)
    cv2.imwrite(f"plots/{imfile_path.name}", im)

    return pixel_corners, gray_im.shape[::-1]

def _find_checkerboard_corners2(tgt_size, imfile_path: Path) -> Any:
    print(f'Loading {imfile_path} ...', file=sys.stderr)
    assert imfile_path.is_file(), f"{imfile_path} is not a valid file"
    im = cv2.imread(str(imfile_path))
    im = im[0:im.shape[0]*5//9, 0:im.shape[1]]
    gray_im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
    plt.imshow(im)

    print('  finding chessboard corners ...', file=sys.stderr)
    pattern_was_found, pixel_corners = cv2.findChessboardCorners(gray_im, tgt_size, flags=cv2.CALIB_CB_FAST_CHECK)
    assert pattern_was_found, f"No corners detected!"
    # cv2.cornerSubPix(gray_im, pixel_corners, (11, 11), (-1, 1), (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001))

    if (pixel_corners[0] > pixel_corners[-1]).all():
        print(f'Flipping reversed checkboard detections for {imfile_path}', file=sys.stderr)
        pixel_corners = pixel_corners[::-1]  # Corners must be top-bottom

    print('  writing corner detection visualization ...', file=sys.stderr)
    cv2.drawChessboardCorners(im, tgt_size, pixel_corners, pattern_was_found)
    cv2.imwrite(f"plots/{imfile_path.name}", im)

    return pixel_corners, gray_im.shape[::-1]


def _load_correspondences_impl(tgt_size, img_file_paths, patch_size: float=20):
    known_target_points = np.zeros((tgt_size[0] * tgt_size[1], 3), np.float32)
    known_target_points[:,:2] = np.mgrid[0:tgt_size[0], 0:tgt_size[1]].T.reshape(-1,2) * patch_size

    correspondences = {}
    for file_path in img_file_paths:
        pixel_corners, im_dimensions = _find_checkerboard_corners(tgt_size, file_path)
        correspondences[file_path] = (known_target_points, pixel_corners, im_dimensions)
    return correspondences

def _load_correspondences_impl2(tgt_size, img_file_paths, patch_size: float=10):
    known_target_points = np.zeros((tgt_size[0] * tgt_size[1], 3), np.float32)
    known_target_points[:,:2] = np.mgrid[0:tgt_size[0], 0:tgt_size[1]].T.reshape(-1,2) * patch_size

    correspondences = {}
    for file_path in img_file_paths:
        pixel_corners, im_dimensions = _find_checkerboard_corners(tgt_size, file_path)
        correspondences[file_path] = (known_target_points, pixel_corners, im_dimensions)
    return correspondences

def load_correspondences_checkerboard(img_file_paths):
    return _load_correspondences_impl((19, 13), img_file_paths)


def load_correspondences_cross_chart(img_file_paths):
    return _load_correspondences_impl2((14, 7), img_file_paths)


def angle_axis_to_matrix(angle_axis: np.ndarray) -> np.ndarray:
    """ Convert a rotation from an angle-axis representation to its
    matrix representation.

    Params
    ------
    `angle_axis`: numpy.ndarray with shape (3,)
        This vector represents a rotation about an axis. Its magnitude
        represents the angle of rotation, in radians, and its (unit-)
        direction represents the axis of rotation. Hence a rotation of
        π/4 about the z-axis would be represented as:
        `np.array([0, 0, np.pi/4])`.

    Returns
    -------
    A unitary, orthonormal, 4x4 transformation matrix that represents the
    same rotation as `angle_axis`.
    """
    magnitude = np.linalg.norm(angle_axis)
    angle, x, y, z = magnitude, *(angle_axis / magnitude)
    K = np.array([ 0, -z,  y,
                   z,  0, -x,
                  -y,  x,  0 ]).reshape(3, 3)
    # Compute exponential map (exp(K)) using Rodriguez's formula
    R = np.eye(3) + (np.sin(angle) * K) + ((1 - np.cos(angle)) * (K @ K))

    matrix_4x4 = np.eye(4)
    matrix_4x4[:3, :3] = R
    return matrix_4x4


def translation_matrix(x: float, y: float, z: float):
    """ Return a 4x4 matrix representating the (x, y, z) translation
    """
    return np.array([[ 1.,  0.,  0.,  x  ],
                     [ 0.,  1.,  0.,  y  ],
                     [ 0.,  0.,  1.,  z  ],
                     [ 0.,  0.,  0.,  1. ]])


def rtvec_to_matrix(rvec, tvec) -> np.ndarray:
    return translation_matrix(*tvec) @ angle_axis_to_matrix(rvec)


def matrix_to_xyzrph(M: np.ndarray):
    tx = M[0, 3]
    ty = M[1, 3]
    tz = M[2, 3]
    rx = np.arctan2(M[2, 1],  M[2, 2])
    ry = np.arctan2(-M[2, 0],  np.sqrt(M[0, 0]*M[0, 0] + M[1, 0]*M[1, 0]))
    rz = np.arctan2(M[1, 0],  M[0, 0])
    return tx, ty, tz, rx, ry, rz

class CameraCalibrationResult(NamedTuple):
    rms_reprojection_err: Any
    cam_mat: Any
    dist_coeffs: Any
    cam_from_target_poses: Any


def calibrate_camera(correspondences):
    obj_points = [ o for o, _i, _s in correspondences.values() ]
    img_points = [ i for _o, i, _s in correspondences.values() ]
    im_shapes = [ s for _o, _i, s in correspondences.values() ]
    assert all( im_shapes[0] == s for s in im_shapes )
    rmse, cam_matrix, dist_coeffs, rvecs, tvecs = cv2.calibrateCamera(obj_points, img_points, im_shapes[0], None, None)
    cam_from_target_poses = [ rtvec_to_matrix(r.squeeze(), t.squeeze()) for r, t in zip(rvecs, tvecs) ]
    return CameraCalibrationResult(rmse, cam_matrix, dist_coeffs, cam_from_target_poses)

def color_negative_red(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    color = 'red' if val < 400 else 'black'
    return 'color: %s' % color


# this_column = df['K1']
# print(len(this_column))
# print (this_column)


def main():
  df_output = pd.DataFrame()

  unit = df['Unit SN']
  pair = df['Pair SN']
  


  for i in range(1,len(unit)-1,2) :

    print (unit[i], pair[i])

    left_cam_mat = load_camera_matrix(i)
    right_cam_mat = load_camera_matrix(i+1)

    #load distortion coefficients
    left_dist_coeff = load_dist_coeff(i)
    right_dist_coeff = load_dist_coeff(i+1)

    print(left_cam_mat, right_dist_coeff)

    lobj_points, limg_points, _ = list(load_correspondences_cross_chart([ Path('/content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_{}_unitSN_{}_left.bmp'.format(pair[i-1],unit[i-1])) ]).values())[0]
    robj_points, rimg_points, _ = list(load_correspondences_cross_chart([ Path('/content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_{}_unitSN_{}_right.bmp'.format(pair[i-1],unit[i])) ]).values())[0]

    _, r, t = cv2.solvePnP(lobj_points, limg_points, left_cam_mat, left_dist_coeff)
    leftcam_from_chart = rtvec_to_matrix(r.squeeze(), t.squeeze())
    
    _, r, t = cv2.solvePnP(robj_points, rimg_points, right_cam_mat, right_dist_coeff)
    rightcam_from_chart = rtvec_to_matrix(r.squeeze(), t.squeeze())
  

    z = matrix_to_xyzrph(leftcam_from_chart @ np.linalg.inv(rightcam_from_chart))
    p = write_trans_rot_errors(z, pair[i-1])
    df_output = df_output.append(pd.DataFrame(p, columns = ['pair SN','translation_x', 'translation_y', 'translation_z','rotation_x','rotation_y','rotation_z']) )

  
  sheet = '/content/gdrive/Shareddrives/External_Primax/Primax/Stereo Calibration/rough_work/Copy of Stereo_Alignment_Data.xlsx'
  # df_output.reset_index(drop=False).style.apply(translation_x_highlight,subset=['translation_x'])
  # df_output.reset_index(drop=False).style.apply(rotation_highlight,subset=['rotation_x','rotation_y','rotation_z'])
  # s = df_output.style.applymap(color_negative_red,['translation_x'])
  # print (s)
  df_output.to_excel(sheet, index = False, engine='openpyxl')
    # applymap(translation_x_highlight,subset=['translation_x']).\
    # pplymap(translation_y_highlight,subset=['translation_y']).\
    # applymap(translation_z_highlight,subset=['translation_z']).\
    # applymap(rotation_highlight,subset=['rotation_x','rotation_y','rotation_z']).\


  time.sleep(10)


  df_new = pd.read_excel(sheet,dtype={'pair SN':'string'})
  df_new.style.\
    applymap(translation_x_highlight,subset=['translation_x']).\
    applymap(translation_y_highlight,subset=['translation_y']).\
    applymap(translation_z_highlight,subset=['translation_z']).\
    applymap(rotation_highlight,subset=['rotation_x','rotation_y','rotation_z']).\
    to_excel(sheet, index = True, engine='openpyxl')

    

if __name__ == '__main__':
    main()


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
000217 000040
[[3.122914e+03 0.000000e+00 1.899300e+03]
 [0.000000e+00 3.112987e+03 1.130179e+03]
 [0.000000e+00 0.000000e+00 1.000000e+00]] [-3.34772717e-01  1.75607776e-01  7.70629769e-05  3.05354194e-04
 -4.55539442e-02]


Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000040_unitSN_000269_left.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000040_unitSN_000269_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000040_unitSN_000217_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000040_unitSN_000217_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000056_unitSN_000268_left.bmp ...
  finding chessboard corners ...


000250 000056
[[3.13213322e+03 0.00000000e+00 1.92864391e+03]
 [0.00000000e+00 3.12079160e+03 1.09165889e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.18932995e-01  1.21941277e-01  2.73010468e-04 -3.43469303e-04
  5.97986508e-03]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000056_unitSN_000268_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000056_unitSN_000250_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000056_unitSN_000250_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000057_unitSN_000481_left.bmp ...
  finding chessboard corners ...


000194 000057
[[3.11897488e+03 0.00000000e+00 1.93399130e+03]
 [0.00000000e+00 3.10755064e+03 1.08803056e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.17948056e-01  1.15348283e-01  5.61343608e-04 -2.19109965e-04
  1.40188401e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000057_unitSN_000481_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000057_unitSN_000194_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000057_unitSN_000194_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000071_unitSN_000275_left.bmp ...
  finding chessboard corners ...


000222 000071
[[3.13197358e+03 0.00000000e+00 1.93302859e+03]
 [0.00000000e+00 3.12162020e+03 1.09045697e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.16624570e-01  1.14597739e-01  6.25827156e-04  1.31150009e-04
  1.19458895e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000071_unitSN_000275_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000071_unitSN_000222_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000071_unitSN_000222_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000073_unitSN_000479_left.bmp ...
  finding chessboard corners ...


000276 000073
[[3.11760103e+03 0.00000000e+00 1.92842958e+03]
 [0.00000000e+00 3.10681263e+03 1.09113627e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.17563846e-01  1.12696700e-01  5.57538394e-04 -1.14514372e-04
  1.70837698e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000073_unitSN_000479_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000073_unitSN_000276_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000073_unitSN_000276_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000087_unitSN_000233_left.bmp ...
  finding chessboard corners ...


000279 000087
[[3.14120930e+03 0.00000000e+00 1.93899475e+03]
 [0.00000000e+00 3.12931978e+03 1.07763134e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.30962786e-01  1.67462541e-01 -2.78647119e-04 -2.05673154e-04
 -4.19103275e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000087_unitSN_000233_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000087_unitSN_000279_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000087_unitSN_000279_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000097_unitSN_000226_left.bmp ...
  finding chessboard corners ...


000443 000097
[[3.12844363e+03 0.00000000e+00 1.91955378e+03]
 [0.00000000e+00 3.11771175e+03 1.12525176e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.35446024e-01  1.87679526e-01  7.32771003e-04 -1.75304293e-04
 -6.44049136e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000097_unitSN_000226_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000097_unitSN_000443_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000097_unitSN_000443_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000101_unitSN_000242_left.bmp ...
  finding chessboard corners ...


000243 000101
[[3.16292117e+03 0.00000000e+00 1.95058766e+03]
 [0.00000000e+00 3.15198304e+03 1.08268605e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.15542833e-01  1.06115503e-01  1.00744661e-04  2.06552187e-04
  2.59188607e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000101_unitSN_000242_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000101_unitSN_000243_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000101_unitSN_000243_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000111_unitSN_000197_left.bmp ...
  finding chessboard corners ...


000140 000111
[[3.12470185e+03 0.00000000e+00 1.92923007e+03]
 [0.00000000e+00 3.11343524e+03 1.07005302e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.18284180e-01  1.16805518e-01 -5.47368640e-05 -7.09967949e-04
  1.28780305e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000111_unitSN_000197_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000111_unitSN_000140_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000111_unitSN_000140_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000115_unitSN_000464_left.bmp ...
  finding chessboard corners ...


000394 000115
[[3.12962077e+03 0.00000000e+00 1.93546801e+03]
 [0.00000000e+00 3.11898892e+03 1.08402146e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.35927137e-01  1.76806596e-01  1.25935367e-03 -2.49854553e-04
 -4.86744625e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000115_unitSN_000464_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000115_unitSN_000394_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000115_unitSN_000394_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000117_unitSN_000234_left.bmp ...
  finding chessboard corners ...


000257 000117
[[3.12741183e+03 0.00000000e+00 1.92905895e+03]
 [0.00000000e+00 3.11636181e+03 1.07042270e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.44450314e-01  2.16002144e-01  6.21276140e-04 -1.56267584e-04
 -9.51706155e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000117_unitSN_000234_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000117_unitSN_000257_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000117_unitSN_000257_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000125_unitSN_000298_left.bmp ...
  finding chessboard corners ...


000157 000125
[[3.13362263e+03 0.00000000e+00 1.92962805e+03]
 [0.00000000e+00 3.12221796e+03 1.08930937e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.35215527e-01  1.76907245e-01  2.55521499e-04 -3.84350498e-04
 -4.70993709e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000125_unitSN_000298_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000125_unitSN_000157_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000125_unitSN_000157_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000126_unitSN_000211_left.bmp ...
  finding chessboard corners ...


000410 000126
[[3.11740676e+03 0.00000000e+00 1.93252789e+03]
 [0.00000000e+00 3.10643166e+03 1.09219210e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.17506725e-01  1.18536040e-01 -1.93164441e-04  1.98222761e-04
  7.92594006e-03]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000126_unitSN_000211_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000126_unitSN_000410_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000126_unitSN_000410_right.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000139_unitSN_000174_left.bmp ...
  finding chessboard corners ...


000219 000139
[[3.12198894e+03 0.00000000e+00 1.92456316e+03]
 [0.00000000e+00 3.11094461e+03 1.08128985e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [-3.37148181e-01  1.94582271e-01 -4.68685186e-04 -9.87378697e-05
 -7.01054468e-02]


Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000139_unitSN_000174_left.bmp
  writing corner detection visualization ...
Loading /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000139_unitSN_000219_right.bmp ...
  finding chessboard corners ...
Flipping reversed checkboard detections for /content/gdrive/Shareddrives/External_Primax/Primax/20210426 15 pairs/Stereo Calibration Images/Bmp/PairSN_000139_unitSN_000219_right.bmp
  writing corner detection visualization ...


In [31]:
sheet = '/content/gdrive/Shareddrives/External_Primax/Primax/Stereo Calibration/rough_work/Copy of Stereo_Alignment_Data.xlsx'

df = pd.read_excel(sheet,dtype={'pair SN':'string'})

df.style.\
  applymap(translation_x_highlight,subset=['translation_x']).\
  applymap(translation_y_highlight,subset=['translation_y']).\
  applymap(translation_z_highlight,subset=['translation_z']).\
  applymap(rotation_highlight,subset=['rotation_x','rotation_y','rotation_z']).\
  to_excel(sheet, index = True, engine='openpyxl')


    Unnamed: 0  Unnamed: 0.1  ...  rotation_y  rotation_z
0            0             0  ...    0.015316    0.002007
1            1             1  ...   -0.004579   -0.003490
2            2             2  ...   -0.037567   -0.006561
3            3             3  ...   -0.000976    0.004595
4            4             4  ...   -0.014773   -0.004907
5            5             5  ...   -0.021480   -0.004262
6            6             6  ...   -0.007323   -0.006130
7            7             7  ...   -0.030448   -0.005455
8            8             8  ...   -0.017832    0.001405
9            9             9  ...   -0.014053   -0.004327
10          10            10  ...   -0.015156   -0.003767
11          11            11  ...   -0.025361   -0.004500
12          12            12  ...   -0.017730   -0.003011
13          13            13  ...   -0.019568    0.001050

[14 rows x 13 columns]
